<?php

/**
 * Litotex - Browsergame Engine
 * Copyright 2017 Das litotex.info Team, All Rights Reserved
 *
 * Website: http://www.litotex.info
 * License: GNU GENERAL PUBLIC LICENSE v3 (https://litotex.info/showthread.php?tid=3)
 *
 */
/*
************************************************************
Litotex BrowsergameEngine
http://www.Litotex.de
http://www.freebg.de

Copyright (c) 2008 FreeBG Team
************************************************************
Hinweis:
Diese Software ist urheberechtlich geschützt.

Für jegliche Fehler oder Schäden, die durch diese Software
auftreten könnten, übernimmt der Autor keine Haftung.

Alle Copyright - Hinweise Innerhalb dieser Datei 
dürfen NICHT entfernt und NICHT verändert werden. 
************************************************************
Released under the GNU General Public License 
************************************************************  
*/
class option
{

    private $dir = "";

    public function __construct($dir)
    {
        $this->dir = $dir;
    }

    public function write()
    {
        global $db, $n, $serverid;
        if ($serverid == "")
        {
            $serverid = 0;
        }
        if(file_exists($this->dir . "options.php"))
        {
            unlink($this->dir . "options.php");
        }
        
        $fp = fopen($this->dir . "options.php", "w");
        $fw = fwrite($fp, "<?PHP\n\n/** DO NOT EDIT THIS FILE - GENERATE WITH CLASS OPTIONS **/\n\n");
        fclose($fp);

        $result = $db->query("SELECT * FROM cc" . $n . "_menu_admin_opt");
        while ($row = $db->fetch_Array($result))
        {
            $fp = fopen($this->dir . "options.php", "a+");
            $new_var = $db->escape_string($row['value']);
            $fw = fwrite($fp, "\$" . $row['varname'] . " = \"" . $new_var . "\";\n");
            fclose($fp);
        }
        $fp = fopen($this->dir . "options.php", "a+");
        $fw = fwrite($fp, "\n");
        fclose($fp);
    }
}