<?php

/**
 * Litotex - Browsergame Engine
 * Copyright 2017 Das litotex.info Team, All Rights Reserved
 *
 * Website: http://www.litotex.info
 * License: GNU GENERAL PUBLIC LICENSE v3 (https://litotex.info/showthread.php?tid=3)
 *
 */
/*
************************************************************
Litotex BrowsergameEngine
http://www.Litotex.de
http://www.freebg.de

Copyright (c) 2008 FreeBG Team
************************************************************
Hinweis:
Diese Software ist urheberechtlich geschützt.

Für jegliche Fehler oder Schäden, die durch diese Software
auftreten könnten, übernimmt der Autor keine Haftung.

Alle Copyright - Hinweise Innerhalb dieser Datei 
dürfen NICHT entfernt und NICHT verändert werden. 
************************************************************
Released under the GNU General Public License 
************************************************************  
*/
class option
{

    public function __construct($dir)
    {
    }

    public function write()
    {
        global $db, $n;
        $this->writeByDB($db, $n);
    }

    public function writeByDB($database, $serverID)
    {
        $dir = LITO_ROOT_PATH . "options" . DIRECTORY_SEPARATOR;
        if (!is_dir($dir))
        {
            _mkdir("options", false);
        }

        if (file_exists($dir . "options.php"))
        {
            unlink($dir . "options.php");
        }

        $fileContent = "<?PHP\n\n/** DO NOT EDIT THIS FILE - GENERATE WITH CLASS OPTIONS **/\n\n";

        $result = $database->query("SELECT * FROM cc" . $serverID . "_menu_admin_opt");
        while ($row = $database->fetch_Array($result))
        {
            $fileContent .= "\$" . $row['varname'] . " = \"" . $database->escape_string($row['value']) . "\";\n";
        }

        file_put_contents($dir . "options.php", $fileContent);
    }
}
